---
apiVersion: v1
kind: ConfigMap

metadata:
  name: api-env

data:
  ENV: dev
  BUILD_INFO_PATH: /app/config/build-info.json
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo-distributor.observability.svc.cluster.local:4318/
  # PYROSCOPE_SERVER_ADDRESS: http://pyroscope.observability.svc.cluster.local:4040
  # PYROSCOPE_TENANT_ID: psw
  SENTRY_RELEASE: "1"
