apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-admin

resources:
    - ../../base
    - configmaps.yaml
    - secrets.yaml
    - pod-monitor.yaml

labels:
    - pairs:
          app: api
          version: v1
          platform: sweetrpg
          package: admin
          component: api

generatorOptions:
    disableNameSuffixHash: true

images:
    - name: admin-api
      newName: ghcr.io/sweetrpg/admin-api
      newTag: latest
