---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: admin-api-cache

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: api-cache
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /sweetrpg/admin/cache/auth
