---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
    name: admin-api-feedback

spec:
    refreshInterval: 1h
    secretStoreRef:
        name: akeyless
        kind: ClusterSecretStore
    target:
        name: api-feedback
        creationPolicy: Owner
    dataFrom:
        - extract:
              key: /sweetrpg/admin/api/feedback
