---
apiVersion: v1
kind: ConfigMap

metadata:
  name: api-env

data:
  ENV: local
  BUILD_INFO_PATH: /app/config/build-info.json
  # OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo-distributor.observability.svc.cluster.local:4318/
  SENTRY_RELEASE: "1"
